# Generated by Django 4.2.2 on 2026-08-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_achievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('focus_label', models.CharField(max_length=100)),
                ('focus_title', models.CharField(max_length=200)),
                ('focus_description', models.TextField()),
            ],
        ),
    ]
