# Generated by Django 4.2.2 on 2026-08-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_skillsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
