# Generated by Django 4.2.2 on 2026-09-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_achievementsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('primary_button_text', models.CharField(max_length=100)),
                ('primary_button_link', models.CharField(max_length=200)),
                ('secondary_button_text', models.CharField(max_length=100)),
                ('secondary_button_link', models.CharField(max_length=200)),
            ],
        ),
    ]
