# Generated by Django 4.2.2 on 2026-09-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_aboutprinciple'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('journey_label', models.CharField(max_length=100)),
                ('journey_text', models.TextField()),
            ],
        ),
    ]
