# Generated by Django 4.2.2 on 2026-09-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_educationprimary_educationrecord_educationsection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FocusSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('eyebrow', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('intro_1', models.TextField()),
                ('intro_2', models.TextField()),
                ('statement_label', models.CharField(max_length=100)),
                ('statement', models.TextField()),
            ],
        ),
    ]
