# Generated by Django 4.2.2 on 2026-09-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_timelineitem_timelinesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('eyebrow', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('email_label', models.CharField(max_length=100)),
                ('github_label', models.CharField(max_length=100)),
                ('linkedin_label', models.CharField(max_length=100)),
                ('instagram_label', models.CharField(max_length=100)),
            ],
        ),
    ]
