# Generated by Django 4.2.2 on 2026-09-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_contactsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.URLField(blank=True),
        ),
    ]
