# Generated by Django 4.2.2 on 2026-09-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_profile_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsection',
            name='more_description',
            field=models.TextField(default='More experiments, applications, and creative projects are currently in development.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectsection',
            name='more_label',
            field=models.CharField(default='MORE PROJECTS', max_length=100),
            preserve_default=False,
        ),
    ]
