# Generated by Django 4.2.2 on 2026-09-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_projectsection_more_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationsection',
            name='learning_label',
            field=models.CharField(default='INDEPENDENT LEARNING', max_length=100),
            preserve_default=False,
        ),
    ]
