# Generated by Django 4.2.2 on 2026-09-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_educationsection_learning_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.TextField()),
                ('copyright_text', models.TextField()),
                ('built_with_text', models.TextField()),
            ],
        ),
    ]
