# Generated by Django 4.2.2 on 2026-09-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_footersection'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsection',
            name='focus_label',
            field=models.CharField(default='FOCUS', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectsection',
            name='levels_label',
            field=models.CharField(default='LEVELS', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectsection',
            name='platform_label',
            field=models.CharField(default='PLATFORM', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectsection',
            name='technology_label',
            field=models.CharField(default='TECHNOLOGY', max_length=100),
            preserve_default=False,
        ),
    ]
