# Generated by Django 4.2.2 on 2026-09-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_projectsection_focus_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelinesection',
            name='current_label',
            field=models.CharField(default='CURRENT', max_length=100),
            preserve_default=False,
        ),
    ]
